version: '3.7'

services:

  ubuntu:
    build:
      context: docker
      dockerfile: Dockerfile.ubuntu
    restart: on-failure
    tty: true
    volumes:
      - ./KURENTO_VERSION:/KURENTO_VERSION
      - ./packages/ubuntu:/packages
      - ./scripts:/scripts
      - ./patches:/patches
      - ./kms:/kms

  amzn2:
    build:
      context: docker
      dockerfile: Dockerfile.amzn2
    restart: on-failure
    tty: true
    volumes:
      - ./KURENTO_VERSION:/KURENTO_VERSION
      - ./docker/rpmmacros:/root/.rpmmacros
      - ./docker/bashrc:/root/.bashrc
      - ./packages/amzn2:/packages
      - ./scripts:/scripts
      - ./rpm:/rpm
      - ./kms:/kms

  el7:
    build:
      context: docker
      dockerfile: Dockerfile.el7
    restart: on-failure
    tty: true
    volumes:
      - ./KURENTO_VERSION:/KURENTO_VERSION
      - ./docker/rpmmacros-el7:/root/.rpmmacros
      - ./docker/bashrc:/root/.bashrc
      - ./packages/el7:/packages
      - ./scripts:/scripts
      - ./rpm:/rpm
      - ./kms:/kms
